In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
a = np.arange(100,116)
a = a.reshape(4,4)
a = a.T
x = a[3].mean()
e = a[0].mean()
f = a[1].mean()
g = a[2].mean()
print(a)
print(x,e,f,g)

[[100 104 108 112]
 [101 105 109 113]
 [102 106 110 114]
 [103 107 111 115]]
109.0 106.0 107.0 108.0


In [13]:
array = np.random.randint(1,101,size=(5,5))
print(array)
array[(array > 50) & (array <80)] = 0
array[array != 0] = 1
print(array)

[[ 17  47  23  97   8]
 [ 95  35  47 100  68]
 [ 42  11  33  44  70]
 [ 81  26  54  86  66]
 [ 57  42  21  58  16]]
[[1 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 0 1 0]
 [0 1 1 0 1]]


In [ ]:
a = np.arange(1,11)
print(a)
a4 = a[a%4==0]
a5 = a[a%5==0]
print(a4)
print(a5)


[ 1  2  3  4  5  6  7  8  9 10]
[4 8]
[ 5 10]


In [15]:
result = np.array([[4,8],[5,10]])
result.T

array([[ 4,  5],
       [ 8, 10]])

In [21]:
p = pd.read_csv("Ecommerce_Purchases.csv")
# p['ExpY'] = pd.to_datetime(p['CC Exp Date']).dt.year
p['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...  
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

In [23]:
fp = {"Almond butter":10,"Blueberries":5,'Eggs':6}
fig, ax = plt.subplots(2,2,figsize=6,4)
ax[2,1].bar(fp.keys(),fp.values())
plt.show()

SyntaxError: positional argument follows keyword argument (4133346945.py, line 2)

In [31]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
 'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
 'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
 'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
 'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

df= pd.DataFrame(raw_data)
# print(df)
print(df[df['regiment'] == 'Nighthawks']['preTestScore'].mean())
print(df.groupby('regiment')['preTestScore'].mean())


15.25
regiment
Dragoons      15.50
Nighthawks    15.25
Scouts         2.50
Name: preTestScore, dtype: float64
