In [11]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats import power
from scipy.stats import ttest_1samp
from scipy.stats import ttest_rel
from scipy.stats import ttest_ind
from scipy.stats import ttest_ind_from_stats
from statsmodels.stats.proportion import  proportions_ztest
from scipy.stats import chisquare # Statistical test (chistat, pvalue)
from scipy.stats import chi2_contingency
from scipy.stats import chi2

### Q1. AI-Based Hiring tool
A startup’s HR department wants to test if their new AI-based hiring tool unfairly rejects qualified female candidates.

They form the hypothesis:

H₀: The tool does not unfairly reject qualified female candidates.
H₁: The tool does unfairly rejects qualified female candidates.
They set a significance level of 0.05 and ran a statistical test. The p-value comes out to 0.07.

What is the best interpretation of their decision and possible error?

In [2]:
H0 = 'Fairly reject female candidates'
HA = 'Unfairly reject female candidates'

alpha = 0.05
p_value = 0.07

if p_value < alpha:
    print(f"Reject the null hypothesis: {HA}")
else:
    print(f"Fail to reject the null hypothesis: {H0}")

Fail to reject the null hypothesis: Fairly reject female candidates


### Q5. Critical Diameter Value
A manufacturing plant is evaluating the average diameter of metal rods produced by a new machine. The rods are expected to have a mean diameter of 5.0 cm, with a standard deviation of 0.2 cm.

To ensure quality, the plant manager wants to find the critical diameter range within which 98% of the rods should fall (i.e., the 98% confidence interval for rod diameter).

Using this information, calculate the critical value for the rod diameter based on a 98% confidence level, assuming the diameter distribution is normal.

In [7]:
pop_mean = 5.0
std_dev = 0.2
confidence_level= 0.98

z_critical = norm.ppf(confidence_level + (1 - confidence_level) / 2)
print(f"Z-critical value: {z_critical}")
margin_of_error = z_critical * std_dev
print(f"Margin of Error: {margin_of_error}")
confidence_interval_range = (pop_mean - margin_of_error, pop_mean + margin_of_error)
print(f"Confidence Interval: {confidence_interval_range}")

Z-critical value: 2.3263478740408408
Margin of Error: 0.46526957480816816
Confidence Interval: (np.float64(4.534730425191832), np.float64(5.465269574808168))


### Q8. Bioequivalence Test for Generic Drug vs Existing Drug
A pharmaceutical company wants to launch a new generic version of an existing cholesterol-lowering drug.

To prove its bioequivalence, it must show that the mean reduction in LDL cholesterol in patients taking the new drug is not significantly different from the existing drug.

Existing Drug: Mean = 35.4 mg/dL, SD = 4.2, n = 80

New Drug: Mean = 34.6 mg/dL, SD = 4.0, n = 75

The company claims bioequivalence, i.e., there's no significant difference. However, a regulatory body tests the hypothesis at α = 0.05.

Which of the following interpretations is most accurate based on a test using the p-value?

In [13]:
H0 = 'There is no significant difference in LDL levels between the two drugs.'
HA = 'There is a significant difference in LDL levels between the two drugs.'

m1 = 35.4
sd1 = 4.2
n1 = 80

m2 = 34.6
sd2 = 4.0
n2 = 75

numerator = m1 - m2
denominator = np.sqrt((sd1**2 / n1) + (sd2**2 / n2))
t_statistic = numerator / denominator
print(f"T-statistic: {t_statistic}")
degrees_of_freedom = (n1 - 1) + (n2 - 1)
print(f"Degrees of Freedom: {degrees_of_freedom}")

t_stat, p_value = ttest_ind_from_stats(mean1=m1, std1=sd1, nobs1=n1, mean2=m2, std2=sd2, nobs2=n2, equal_var=True)
print(f"T-statistic: {t_stat}, P-value: {p_value}")

alpha = 0.05
if p_value < alpha:
    print(f"Reject the null hypothesis: {HA}")
else:
    print(f"Fail to reject the null hypothesis: {H0}")

T-statistic: 1.21458671940818
Degrees of Freedom: 153
T-statistic: 1.2126656802892282, P-value: 0.22712676575082538
Fail to reject the null hypothesis: There is no significant difference in LDL levels between the two drugs.


### Q9. Comparing Average Daily Steps Between Android and iPhone Users
A fitness tracker company wants to test if there's any significant difference in average daily steps between Android users and iPhone users.

Sample data:

Android: mean = 7,800, std = 1,200, n = 20

iPhone: mean = 8,100, std = 1,250, n = 20

Assuming equal variances and α = 0.05, what is the most statistically accurate interpretation?

In [39]:
H0 = 'No significant difference in steps'
HA = 'Significant difference in steps'
alpha = 0.05

t_stat, p_value = ttest_ind_from_stats(mean1=7800, std1=1200, nobs1=20, mean2=8100, std2=1250, nobs2=20, equal_var=True)
print(f"T-statistic: {t_stat}, P-value: {p_value}")

if p_value < alpha:
    print(f"Reject the null hypothesis: {HA}")
else:
    print(f"Fail to reject the null hypothesis: {H0}")

T-statistic: -0.7742741222072023, P-value: 0.44355965712636036
Fail to reject the null hypothesis: No significant difference in steps


### Q10. Testing Difference in Email Open Rates Between Subject Lines A and B
A marketing analyst compares the effectiveness of two email subject lines by measuring open rates:

Subject Line A: 310 opens out of 1000
Subject Line B: 270 opens out of 900
A statistical test is conducted at α = 0.05 to determine if there's a significant difference in open rates.

However, her manager concludes, "Subject Line A is more effective when compared to Subject Line B."

Which interpretation below is statistically valid based on the p-value from the test?

In [17]:
HO = 'Subject Line A is less than or equal significant than subject line B.'
HA = 'Subject Line A is more significant than Subject Line B.'

p_a = 310/1000
p_b = 270/900

open_rates = np.array([310, 270])
counts = np.array([1000, 900])

stat, p_value = proportions_ztest(count=open_rates, nobs=counts, alternative='two-sided')
print(f"Z-statistic: {stat}, P-value: {p_value}")

alpha = 0.05
if p_value < alpha:
    print(f"Reject the null hypothesis: {HA}")
else:
    print(f"Fail to reject the null hypothesis: {HO}")

Z-statistic: 0.4726036732558498, P-value: 0.636495961335126
Fail to reject the null hypothesis: Subject Line A is less than or equal significant than subject line B.


### 
A psychologist is testing whether a cognitive training program improves memory scores in participants. She measures the memory scores of 20 participants before and after completing the program.

The results show:

before_scores = [58, 62, 64, 54, 55, 59, 60, 63, 55, 56, 62, 61, 59, 64, 58, 57, 60, 63, 58, 59]

after_scores = [63, 67, 68, 57, 60, 64, 61, 66, 58, 59, 64, 63, 60, 67, 61, 60, 62, 65, 60, 61]

The psychologist performs an appropriate test at 0.05 to test if the program significantly improves scores. Which of the following interpretations is statistically valid based on the p-value from the test?

In [32]:
H0 = 'Scores has no impact'
HA = 'Scores are improved after the training'
before_scores = [58, 62, 64, 54, 55, 59, 60, 63, 55, 56, 62, 61, 59, 64, 58, 57, 60, 63, 58, 59]

after_scores = [63, 67, 68, 57, 60, 64, 61, 66, 58, 59, 64, 63, 60, 67, 61, 60, 62, 65, 60, 61]

alpha = 0.05
t_statistic, p_value = ttest_rel(after_scores, before_scores,alternative='greater')
print(f"T-statistic: {t_statistic}, P-value: {p_value},t_stat:{t_statistic:.4f} p_rounded: {p_value:.10f}")

if p_value < alpha:
    print(f"Reject the null hypothesis: {HA}")
else:
    print(f"Fail to reject the null hypothesis: {H0}")

T-statistic: 10.33673750100978, P-value: 1.5394510318795526e-09,t_stat:10.3367 p_rounded: 0.0000000015
Reject the null hypothesis: Scores are improved after the training


### Q13. Ticket Sales Test
A local theater group wants to test whether the distribution of ticket sales for their five shows matches the expected uniform distribution. The expected number of sales for each show is 200 tickets. After selling tickets for a month, the actual sales are:

Show 1 → 190 tickets  
Show 2 → 210 tickets  
Show 3 → 195 tickets  
Show 4 → 230 tickets  
Show 5 → 175 tickets

They decide to perform a test at α = 0.10 to see if the actual sales differ significantly from the expected uniform distribution (i.e., each show is expected to sell 200 tickets).

Which of the following interpretations is statistically valid based on the p-value from the test?

In [33]:
H0 = 'The sales are uniform across all 5 shows'
HA = 'The sales are not uniform across all 5 shows'
expected = [200,200,200,200,200]
observed = [190,210,195, 230, 175]

chi_statistic, p_value = chisquare(f_obs=observed, f_exp=expected)
print(f"Chi-square statistic: {chi_statistic}, P-value: {p_value}")
alpha = 0.1

if p_value < alpha:
    print(f"Reject the null hypothesis: {HA}")  
else:
    print(f"Fail to reject the null hypothesis: {H0}")

Chi-square statistic: 8.75, P-value: 0.06766126455308273
Reject the null hypothesis: The sales are not uniform across all 5 shows


### Q14. Product Preference Test
A market researcher wants to analyze if product preference is independent of age group. The following summarizes the preferences of 500 customers across three age groups:

<img src="ProductAgeGroup.png" style="width:300px;height:200px">

The researcher tests independence of product preference and age group at alpha = 0.05 .

Which of the following interpretations is statistically valid based on the p-value from the test?

In [34]:
H0 = 'Product preference is independent of age'
HA = 'Product preference is dependent on age'
data = [
    [100, 50, 30],
    [90, 60, 20],
    [60, 40, 50]
]
alpha = 0.05
chi2_statistic, p_value, dof, expected = chi2_contingency(data)
print(f"Chi-square statistic: {chi2_statistic}, P-value: {p_value}, Degrees of Freedom: {dof}")
print(f"Expected Frequencies: \n{expected}")

if p_value < alpha:
    print(f"Reject the null hypothesis: {HA}")
else:   
    print(f"Fail to reject the null hypothesis: {H0}")

Chi-square statistic: 26.94335511982571, P-value: 2.0410030386493665e-05, Degrees of Freedom: 4
Expected Frequencies: 
[[90. 54. 36.]
 [85. 51. 34.]
 [75. 45. 30.]]
Reject the null hypothesis: Product preference is dependent on age
