<a href="https://colab.research.google.com/github/sdadi/ScalerDSML/blob/main/1_numpy%5Cnump1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
type(a)

list

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
#square each and every element
res = [i**2 for i in a]
res

[1, 4, 9, 16, 25]

In [ ]:
#define the numpy array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
#square each and every element for this array
a**2 #no loops, cleaner #numpy supports vectorization/ parallel processing -> one operation on the entire array

array([ 1,  4,  9, 16])

In [ ]:
#performance comparison

In [ ]:
l = range(1000000)
%timeit [i**2 for i in l]

89.8 ms ± 20.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
l_np = np.array(range(1000000))
%timeit l_np**2

709 µs ± 80.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
#why numpy faster => dense,contiguous block , run on compiled c code, not python loops

#numpy array

In [ ]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#dimensions, shape
arr1.ndim #directions it has , how many levels you have

1

In [ ]:
#2d
arr2 = np.array([[1,2,3,5],[4,5,6,5],[7,8,9,5]])
arr2

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 8, 9, 5]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2.ndim

2

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1.shape #tuple = 1d => element in 1 direction

(10,)

In [ ]:
#What will be the output of the following code?
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
#number sequnces
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array(range(1,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
#np.arange() #can work with ints as well as floats
arr = np.arange(1,5,0.5)

In [ ]:
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
arr2 = np.array([1,2,3,4.0])
arr2

array([1., 2., 3., 4.])

In [ ]:
arr2 = np.array([1,2,3,4.0,'praveen'])
arr2

array(['1', '2', '3', '4.0', 'praveen'], dtype='<U32')

In [ ]:
#manually specify data types while creating the array
arr2 = np.array([1,2,3,4],dtype='float')
arr2

array([1., 2., 3., 4.])

In [ ]:
arr2 = np.array([1,2,3,4,4.5],dtype='int')
arr2

array([1, 2, 3, 4, 4])

In [ ]:
arr2 = np.array([1,2,3,4,4.5],dtype='str')
arr2

array(['1', '2', '3', '4', '4.5'], dtype='<U3')

In [ ]:
arr2 = np.array([1,2,3,4,'a','b'],dtype='int')
arr2

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
arr2 = np.array([1,2,3,4,'1','2'],dtype='int')
arr2

array([1, 2, 3, 4, 1, 2])

In [ ]:
#homework
arr2 = np.array([1,2,3,4,'1','2.5'],dtype='int')
arr2

In [ ]:
#can i change the type of array after creation
arr = np.array([10,20,30])
arr #int => float

array([10, 20, 30])

In [ ]:
arr.astype('float')


array([10., 20., 30.])

In [ ]:
#access elements in a numpy array
#indexing
#slicing



In [ ]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[0]

np.int64(0)

In [ ]:
m1[5]

np.int64(5)

In [ ]:
m1[-1]

np.int64(11)

In [ ]:
#advanced indexing
m1 = np.array([100,200,300,400,500,600])
m1

array([100, 200, 300, 400, 500, 600])

In [ ]:
m1[[1,2,1,3,4,2,2]] #you can pass the indexes in the form of list #fancy indexing

array([200, 300, 200, 400, 500, 300, 300])

In [ ]:
m1[1,2,1,3,4,4] #single indexing => 1d => error

In [ ]:
m1[[1,2,1,3,4,-4]] #list form

array([200, 300, 200, 400, 500, 300])

In [ ]:
#slicing => continuous subpart of the array

In [ ]:
m1 = np.arange(10,20)
m1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#first 5 elemnts => subpart
m1[:5]

array([10, 11, 12, 13, 14])

In [ ]:
m1[-5:-1]

array([15, 16, 17, 18])

In [ ]:
m1[-5:-1:-1]

array([], dtype=int64)

In [ ]:
m1[-1:-5:-1]

array([19, 18, 17, 16])

In [ ]:
#What will be the output of the following code?
import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
import numpy as np
a = np.array([0,1,2,3,4,5])
a[::2] = 10
print(a)

[10  1 10  3 10  5]


#working on 2d arrays

In [ ]:
a = np.array(range(16))
print(a)
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


(16,)

In [ ]:
a.ndim

1

In [ ]:
#1d to 2d array => reshape()
a.reshape(8,8)

ValueError: cannot reshape array of size 16 into shape (8,8)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(4,4) #new array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(1,16) #2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(16,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(16,1) #2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [ ]:
a.reshape(8,-1,1)

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [5]:
a = np.arange(10)
np.split(a,[5,12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]