In [17]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats import power
from scipy.stats import ttest_1samp
from scipy.stats import ttest_rel
from scipy.stats import ttest_ind
from statsmodels.stats.proportion import  proportions_ztest
from scipy.stats import chisquare # Statistical test (chistat, pvalue)
from scipy.stats import chi2_contingency
from scipy.stats import chi2

### Q1. Test the Training Program
You are appointed as a Data Analyst for a training program deployed by the Government of India.

The participants’ skills were tested before and after the training using some metrics on a scale of 10.

before = [2.45, 0.69, 1.80, 2.80, 0.07, 1.67, 2.93, 0.47, 1.45, 1.34]   

after = [7.71, 2.17, 5.65, 8.79, 0.23, 5.23, 9.19, 1.49, 4.56, 4.20] 
Conduct an appropriate test to assess a statistically significant increase in the average skill score after the training program, and then answer the below questions accordingly.

Note: Perform the test at alpha = 5%.

In [7]:
# H0: There is no significant increase in average skill score after the training program.
# H1: There is a significant increase in average skill score after the training program.

before = [2.45, 0.69, 1.80, 2.80, 0.07, 1.67, 2.93, 0.47, 1.45, 1.34]   
after = [7.71, 2.17, 5.65, 8.79, 0.23, 5.23, 9.19, 1.49, 4.56, 4.20] 

t_test, p_value = ttest_rel(after, before)
print(f't-statistic: {t_test}')
print(f'p-value: {p_value}')

alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant increase in the average skill score after the training program.")
else:
    print("Fail to reject the null hypothesis: There is no significant increase in the average skill score after the training program.")

t-statistic: 5.111096450191605
p-value: 0.0006355623963896455
Reject the null hypothesis: There is a significant increase in the average skill score after the training program.


### Q2. Zumba traine
The Zumba trainer claims to the customers, that their new dance routine helps to reduce more weight.

Weight of 8 people were recorded before and after following the new Zumba training for a month:

wt_before = [85, 74, 63.5, 69.4, 71.6, 65,90,78]

wt_after = [82, 71, 64, 65.2, 67.8, 64.7,95,77]

Test the trainer's claim with 90% confidence. Further, what would be the pvalue?

In [13]:
wt_before = [85, 74, 63.5, 69.4, 71.6, 65,90,78]
wt_after = [82, 71, 64, 65.2, 67.8, 64.7,95,77]

t_test, p_value = ttest_rel(wt_after, wt_before,alternative='less')
print(f't-statistic: {t_test}')
print(f'p-value: {p_value}')

alpha = 0.10  # 90% confidence level corresponds to alpha = 1 - 0.90 = 0.10

if p_value < alpha:
    print("Reject the null hypothesis: There is a significant decrease in the average weight after the diet program.")
else:
    print("Fail to reject the null hypothesis: There is no significant decrease in the average weight after the diet program.")

t-statistic: -1.1421853793555032
p-value: 0.14546808501326386
Fail to reject the null hypothesis: There is no significant decrease in the average weight after the diet program.


### Q3. Effectiveness on yield
An experiment was performed to compare the effectiveness of Ammonium Chloride and urea on the grain yield (in quintal per hectare) and the results are given in the arrays below:

Ammonium_chloride = [13.4, 10.9, 11.2, 11.8, 14, 15.3, 14.2, 12.6, 17, 16.2, 16.5, 15.7]
Urea = [12, 11.7, 10.7, 11.2, 14.8, 14.4, 13.9, 13.7, 16.9, 16, 15.6, 16]
Conduct an appropriate test to compare the same with a 95% confidence level and choose the appropriate option below.

In [18]:
Ammonium_chloride = [13.4, 10.9, 11.2, 11.8, 14, 15.3, 14.2, 12.6, 17, 16.2, 16.5, 15.7]
Urea = [12, 11.7, 10.7, 11.2, 14.8, 14.4, 13.9, 13.7, 16.9, 16, 15.6, 16]
confidence_level = 0.95
alpha = 1 - confidence_level

t_test, p_value = ttest_ind(Urea, Ammonium_chloride)
print(f't-statistic: {t_test}')
print(f'p-value: {p_value}')

if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference in grain yield between Ammonium Chloride and Urea.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in grain yield between Ammonium Chloride and Urea.")

t-statistic: -0.1846496543760765
p-value: 0.8551954147800473
Fail to reject the null hypothesis: There is no significant difference in grain yield between Ammonium Chloride and Urea.


### Q4. Coaching class
There are 8 females and 12 males in a coaching class.

After a practice test, the coach wants to know whether the average score of females is greater than the average score of males.

Given data describes the scores of females and males in his class.

female_scores=[25,30,45,49,47,35,32,42]

male_scores=[45,47,25,22,29,32,27,28,40,49,50,33]
Use an appropriate test to check whether the assumption of the coach is significant or not, at a 2% significance level?

In [20]:
# H0: avg of male and female are less than or equal
# HA: avg of female is greater than avg of male

female_scores=[25,30,45,49,47,35,32,42]
male_scores=[45,47,25,22,29,32,27,28,40,49,50,33]
alpha = 0.02

t_test, p_value = ttest_ind(female_scores, male_scores, alternative='greater')
print(f't-statistic: {t_test}')
print(f'p-value: {p_value}')

if p_value < alpha:
    print("Reject the null hypothesis: The average score of female students is significantly greater than that of male students.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in average scores between female and male students.")

t-statistic: 0.5795450171026676
p-value: 0.2847023809445894
Fail to reject the null hypothesis: There is no significant difference in average scores between female and male students.


### Q5. Help to choose the right test
A telecom company had taken a survey of smartphone owners in a certain town 5 years back and found 73% of the population own a smartphone, and have been since using this data to make their business decisions.

Now a new marketing manager has joined, and he believes this value is not valid anymore. Thus he conducts a survey of 500 people and finds that 420 of them responded with affirmation as to owning a smartphone.

Which statistical test would you use to compare these two survey data?

In [ ]:
# Answer: Test of proportions, z-test


### Q6. Marital Status and Drinking
A national survey was conducted to obtain information on the alcohol consumption patterns of U.S. adults by marital status.
A random sample of 1772 residents, aged 18 and older, yielded the data displayed in Table below:

<img src="MaritalStatusDrinks.png" style="width=200px;height:200px;">

Test whether Marital status and alcohol consumption are associated with a 5% significance level.

Choose the correct option below :

In [23]:
# H0: Marital Status and Drintks are not related
# HA: Marital Status and Drintks are related

sample_size = 1772
alpha = 0.05
data = [[67, 213, 74], 
        [411, 633, 129], 
        [85, 51, 7], 
        [27, 60, 15]]
chi2_stat, p_value, dof, expected = chi2_contingency(data)
print(f'Chi-square statistic: {chi2_stat}')
print(f'p-value: {p_value}')
print(f'Degrees of freedom: {dof}')
print(f'Expected frequencies: \n{expected}')

if p_value < alpha:
    print("Reject the null hypothesis: Marital Status and Drinks are related.")
else:
    print("Fail to reject the null hypothesis: Marital Status and Drinks are not related.")

print(f'p_value = {p_value}, Marital status and alcohol consumption are associated.')    

Chi-square statistic: 94.26880078578765
p-value: 3.925170647869838e-18
Degrees of freedom: 6
Expected frequencies: 
[[117.86681716 191.18397291  44.94920993]
 [390.55869074 633.49943567 148.94187359]
 [ 47.61286682  77.22968397  18.15744921]
 [ 33.96162528  55.08690745  12.95146727]]
Reject the null hypothesis: Marital Status and Drinks are related.
p_value = 3.925170647869838e-18, Marital status and alcohol consumption are associated.


### Internet Use
A random sample of adults yielded the following data on age and Internet usage.

<img src="AgeInternetUsage.png" style="width=200px;height:200px;">


At 1% significance level, does the data provide sufficient evidence to conclude that an association exists between age and Internet usage?


In [ ]:
# H0: Age and Internet usage are not related
# HA: Age and Internet usage are related

data = [
    [6,38,31],
    [14, 31, 4],
    [50, 50, 5]
]
alpha = 0.01

chi2_stat, p_value, dof, expected = chi2_contingency(data)
print(f'Chi-square statistic: {chi2_stat}')
print(f'p-value: {p_value}')
print(f'Degrees of freedom: {dof}')
print(f'Expected frequencies: \n{expected}')

if p_value < alpha:
    print("Reject the null hypothesis: No association between Age and Internet usage.")
else:
    print("Fail to reject the null hypothesis: There is an association between Age and Internet usage.")

print(f'Answer: p_value = {p_value}, There is NO association between Age and Internet usage.')    

Chi-square statistic: 60.74604310295546
p-value: 2.0217185191724964e-12
Degrees of freedom: 4
Expected frequencies: 
[[22.92576419 38.97379913 13.10043668]
 [14.97816594 25.4628821   8.55895197]
 [32.09606987 54.56331878 18.34061135]]
Reject the null hypothesis: No association between Age and Internet usage.
Answer: p_value = 2.0217185191724964e-12, There is NO association between Age and Internet usage.
